# docker-compose -f docker-compose.static.yml up
version: '3'

services:
  nginx:
    image: nginx:1.24.0
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docs/_site:/var/www/html
      - /etc/nginx/sites-available
    ports:
      - 80:80
