repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude_types: [csv, svg, markdown]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: mixed-line-ending
        args: ['--fix=lf']
        exclude_types: [csv, svg]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.2.1' # Use the sha or tag you want to point at
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: ember-template-lint
        name: ember-template-lint
        entry: node_modules/.bin/ember-template-lint
        language: script
        files: \.hbs$
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: node_modules/.bin/eslint
        language: script
        files: \.js$
