title: Roadmap
repository: a-mt/dev-roadmap

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      summary: true

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata

theme: jekyll-theme-primer
sass:
  quiet_deps: true  # don't print warnings caused by dependencies
